"""Add agent task relations and assoc tables

Revision ID: 1720c3453354
Revises: fff3edbb0ffa
Create Date: 2025-03-25 21:05:25.065411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1720c3453354'
down_revision = 'fff3edbb0ffa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='agenttaskstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('video_urls', sa.JSON(), nullable=False),
    sa.Column('destination_note_id', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['destination_note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_task_id'), 'agent_task', ['id'], unique=False)
    op.create_index(op.f('ix_agent_task_organization_id'), 'agent_task', ['organization_id'], unique=False)
    op.create_table('agent_task_modified_notes',
    sa.Column('agent_task_id', sa.String(), nullable=False),
    sa.Column('note_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_task_id'], ['agent_task.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.PrimaryKeyConstraint('agent_task_id', 'note_id')
    )
    op.create_table('agent_task_reference_notes',
    sa.Column('agent_task_id', sa.String(), nullable=False),
    sa.Column('note_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agent_task_id'], ['agent_task.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.PrimaryKeyConstraint('agent_task_id', 'note_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_task_reference_notes')
    op.drop_table('agent_task_modified_notes')
    op.drop_index(op.f('ix_agent_task_organization_id'), table_name='agent_task')
    op.drop_index(op.f('ix_agent_task_id'), table_name='agent_task')
    op.drop_table('agent_task')
    # ### end Alembic commands ###