"""auto migration

Revision ID: 2ba364148c52
Revises: 4ef6e8f168f9
Create Date: 2025-01-20 12:28:53.375015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba364148c52'
down_revision = '4ef6e8f168f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###