"""auto migration

Revision ID: 2e217367b8f1
Revises: 41e8a271e5ae
Create Date: 2025-02-02 09:15:56.507327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e217367b8f1'
down_revision = '41e8a271e5ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###