"""auto migration

Revision ID: 395d88cf36d5
Revises: 5c352c244895
Create Date: 2025-02-06 21:44:56.929010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395d88cf36d5'
down_revision = '5c352c244895'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###