"""auto migration

Revision ID: 3ac511716e98
Revises: 2ba364148c52
Create Date: 2025-01-20 12:30:20.881549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac511716e98'
down_revision = '2ba364148c52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###