"""auto migration

Revision ID: 41e8a271e5ae
Revises: 34b392511276
Create Date: 2025-02-02 08:46:50.339130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e8a271e5ae'
down_revision = '34b392511276'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###