"""auto migration

Revision ID: 5ab1c9372c1b
Revises: 6ab4c18081c4
Create Date: 2025-02-07 12:45:57.058315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab1c9372c1b'
down_revision = '6ab4c18081c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###