"""auto migration

Revision ID: 6ab4c18081c4
Revises: 395d88cf36d5
Create Date: 2025-02-07 12:44:59.036886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab4c18081c4'
down_revision = '395d88cf36d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###