"""auto migration

Revision ID: 71a8c6aadb54
Revises: f0d7c41306f9
Create Date: 2025-01-21 08:19:47.365517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a8c6aadb54'
down_revision = 'f0d7c41306f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###