"""adding suggestion for new note creation

Revision ID: 7a49ef643449
Revises: 1720c3453354
Create Date: 2025-03-28 22:46:32.982771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a49ef643449'
down_revision = '1720c3453354'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('suggestion_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'suggestion_content')
    # ### end Alembic commands ###