"""adding title to each agent task

Revision ID: 8621d0b82bfb
Revises: 7a49ef643449
Create Date: 2025-03-30 12:15:59.064321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8621d0b82bfb'
down_revision = '7a49ef643449'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_task', sa.Column('title', sa.String(), nullable=True))
    op.execute("UPDATE agent_task SET title = 'Dummy Task Title'")
    op.alter_column('agent_task', 'title', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_task', 'title')
    # ### end Alembic commands ###