"""auto migration

Revision ID: 98ea1b45f197
Revises: 5ab1c9372c1b
Create Date: 2025-02-07 12:48:00.369418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ea1b45f197'
down_revision = '5ab1c9372c1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###