"""auto migration

Revision ID: b533196b9cfb
Revises: 86d9be05b3b9
Create Date: 2025-02-01 20:03:49.543455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b533196b9cfb'
down_revision = '86d9be05b3b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###