"""auto migration

Revision ID: ddfc2d7e6e62
Revises: de764f36c434
Create Date: 2025-01-20 12:27:39.352664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddfc2d7e6e62'
down_revision = 'de764f36c434'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###